In [3]:
#importing the necessary libraries and modules
import numpy as np
import matplotlib as plt
from scipy.stats import mode
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from math import sqrt
from sklearn.preprocessing import normalize

In [4]:
#Define the KNN Classifier class
class KnnClassifier:
    
    def __init__(self, k = 5, p = 2):
        # initialize the number of neighbors to use
        self.neighbors = k
        self.pnorm = p
        
    

    #Defining the fit() Function to feed the data to the model
    def fit(self,X,Y):
        
        self.classes = np.unique(Y)
        #if there is only one class then there is no classification 
        if (self.classes) < 2:
            print("Less number of classes")
        
        #Assign labels to Y and Drespective data to X
        self.data = X
        self.labels = Y 
        
        
        
    
    #defining the predict function to predict the values
    def predict(self,X):
        
        yPredicted = np.empty([X.shape[0],1])
        
        for row in range(X.shape[0]):
            datapoint = X[row,]
            
            # different scenarios for pnorm 
            #When pnorm is not equal to inifinity , manhattan and eucledian are the special case.
            if self.pnorm!= np.inf:
              # find the distances from the datapoint to each training point using the Lp norm
              distances = (np.sum(((self.data - datapoint) ** self.pnorm), axis=1))
              distances = np.sign(distances)*(np.abs(distances)) ** (1 / float(self.pnorm))
            else:
              # Scenario of pnorm when it is equal infinity
              distances = np.amax(np.abs(self.data - datapoint))
            #getting the locations of the nerest neighbors
            indices = np.argsort(distances)[:self.neighbors]
            nearestClasses = self.labels[indices]
            #getting the predicted label
            yPredicted[row] = int(mode(nearestClasses)[0][0])
        #return the predicted value
        return yPredicted
        

In [ ]:
#training data
trainX = np.array([[1, 2], [3, 4], [-1, 3], [4, 2], [2, 2], [1, 1], [2, 3], [3, 3]])
trainY = np.array([1, 0, 1, 1, 0, 0, 1, 0])

#testing data
testX = np.array([[4, 3], [0, 0], [1, 4], [2, 1]])
testY = np.array([1, 1, 1, 0])

#K = sqrt(len(testX))
print(len(testX))

#For better accuracy trying k value as root of number of datapoints
K = sqrt(len(testX))
if(K%2 == 0 and K == 2):
    K=3
elif(K%2 == 0):
    k = k -1
else:
    K = K

#Different values of K   
for p in range (1,5):
    if (p == 4):
      p = np.inf
    for neigbhors in range (2,15):
      model = KnnClassifier( k = K , p = np.inf)
      print( "K : " + str(neigbhors) + " , P : " + str(p))
      trainX = normalize(trainX)
      testX = normalize(testX)
      #fit the data in the model
      model.fit(trainX, trainY)
      predictions = model.predict(testX)
      #Predict the output
      print(predictions.T[0])
      print(testY)
      #print classification reports
      print(classification_report(testY, predictions))
      print("acc")
      accuracy = accuracy_score(testY, model.predict(testX))
      print(accuracy)

4
K : 2 , P : 1
[1. 1. 1. 1.]
[1 1 1 0]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.75      1.00      0.86         3

    accuracy                           0.75         4
   macro avg       0.38      0.50      0.43         4
weighted avg       0.56      0.75      0.64         4

acc
0.75
K : 3 , P : 1
[1. 1. 1. 1.]
[1 1 1 0]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.75      1.00      0.86         3

    accuracy                           0.75         4
   macro avg       0.38      0.50      0.43         4
weighted avg       0.56      0.75      0.64         4

acc
0.75
K : 4 , P : 1
[1. 1. 1. 1.]
[1 1 1 0]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.75      1.00      0.86         3

    accuracy                           0.75     

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classificat

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.75      1.00      0.86         3

    accuracy                           0.75         4
   macro avg       0.38      0.50      0.43         4
weighted avg       0.56      0.75      0.64         4

acc
0.75
K : 11 , P : 2
[1. 1. 1. 1.]
[1 1 1 0]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.75      1.00      0.86         3

    accuracy                           0.75         4
   macro avg       0.38      0.50      0.43         4
weighted avg       0.56      0.75      0.64         4

acc
0.75
K : 12 , P : 2
[1. 1. 1. 1.]
[1 1 1 0]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.75      1.00      0.86         3

    accuracy                           0.75         4
   macro avg       0.38      0.5

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classificat

[1. 1. 1. 1.]
[1 1 1 0]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.75      1.00      0.86         3

    accuracy                           0.75         4
   macro avg       0.38      0.50      0.43         4
weighted avg       0.56      0.75      0.64         4

acc
0.75
K : 7 , P : inf
[1. 1. 1. 1.]
[1 1 1 0]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.75      1.00      0.86         3

    accuracy                           0.75         4
   macro avg       0.38      0.50      0.43         4
weighted avg       0.56      0.75      0.64         4

acc
0.75
K : 8 , P : inf
[1. 1. 1. 1.]
[1 1 1 0]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.75      1.00      0.86         3

    accuracy                           0.75         4
   mac

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classificat